name: NodeJS with Webpack

on:
  push:
    branches:
      - main
      - saikiran
  pull_request:
    branches:
      - main
      - saikiran

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Angular CLI
        run: |
          rm -rf node_modules
          npm install -g @angular/cli

      - name: Install @ng-bootstrap/ng-bootstrap
        run: npm install --legacy-peer-deps

      - name: Build
        run: |
          ng build --prod
          dir

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: mohammedaggoun.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          remote-dir: ${{ github.ref == 'refs/heads/main' && '/public_html/v1/' || github.ref == 'refs/heads/saikiran' && '/public_html/v2/' || '/public_html/other/' }}
